#ifndef ROOT_H
#define ROOT_H

#include <TApplication.h>
#include <TCanvas.h>
#include <TEnv.h>
#include <TFile.h>
#include <TFileDrawMap.h>
//#include <TFileSet.h>
#include <TF1.h>
#include <TF2.h>
#include <TF3.h>
#include <TText.h>
#include <TColor.h>
#include <TPaveText.h>
#include <TKey.h>
#include <TGButton.h>
#include <TGCanvas.h>
#include <TGClient.h>
#include <TGColorSelect.h>
#include <TGComboBox.h>
#include <TGDoubleSlider.h>
#include <TGFrame.h>
#include <TGFileDialog.h>
#include <TGFSContainer.h>
#include <TGIcon.h>
#include <TGLabel.h>
#include <TGListBox.h>
#include <TGListTree.h>
#include <TGMenu.h>
#include <TGMsgBox.h>
#include <TGNumberEntry.h>
#include <TGProgressBar.h>
#include <TGraph.h>
#include <TGraphAsymmErrors.h>
#include <TGraphBentErrors.h>
#include <TGraphDelaunay.h>
#include <TGraphErrors.h>
#include <TGraphPainter.h>
#include <TGraphSmooth.h>
#include <TGraph2DErrors.h>
#include <TGResourcePool.h>
#include <TGShutter.h>
#include <TGSlider.h>
#include <TGTab.h>
#include <TGTextEdit.h>
#include <TGTextEntry.h>
#include <TMath.h>
#include <TH1.h>
#include <TH2.h>
#include <TH3.h>
#include <TPostScript.h>
#include <TPad.h>
#include <TPaveStats.h>
#include <TRandom.h>
#include <TROOT.h>
#include <TRootEmbeddedCanvas.h>
#include <TStyle.h>
#include <TSystem.h>
#include <TSystemDirectory.h>
#include <TTree.h>
#include <TLeaf.h>
#include <TVirtualX.h>


#endif
